app.py
from flask import Flask, redirect, url_for
from common.database import Database
#from utils.scheduler_utils import SchedulerUtils
import threading

app = Flask(__name__)

@app.before_first_request
def init_db():
    Database.initialize()
    #t = threading.Thread(target=SchedulerUtils.init_schedule)
    #t.start()


@app.route('/')
def home():
    return redirect(url_for('weight.register_weight'))


from blueprints.weight import weight_blueprint

app.register_blueprint(weight_blueprint, url_prefix='/weight')


if __name__ == '__main__':
    app.run(port=8080, host="0.0.0.0", threaded=True)

blueprints/weight.py
from flask import Blueprint, request, url_for, render_template, Response
from common.database import Database
import json

#import error as Errors

weight_blueprint = Blueprint('weight', __name__)


@weight_blueprint.route('/register', methods=['POST', 'GET'])
def register_weight():
    if request.method == 'GET':
        status, avg_values, day_in_week, unit = Database.getHistoryInWeeks(0)
        if status == 'OK' and avg_values and unit:
            return render_template('index.html', last_week_avg=avg_values[0], unit=unit)
        return render_template('index.html')
    elif request.method == 'POST':
        content = request.get_json()
        todays_weight = content['todays_weight']
        unit = content['unit']
        result, last_week_avg = Database.saveToDb(todays_weight, unit)
        if result == 'OK':
            return Response(json.dumps({"weight": todays_weight, "unit": unit, 'last_week_avg': last_week_avg if last_week_avg else None ,"error":None}),status=201, mimetype="application/json")
        else:
            return Response(json.dumps({'error':'There was an error'}), status=500, mimetype="application/json")


@weight_blueprint.route('/history', methods=['GET'])
def show_history():
    options = [i for i in range(1,100)]
    return render_template('history.html', options=options)


@weight_blueprint.route('/historydays', methods=['GET'])
def show_days():
    amount = request.args.get('amount')
    result, values, days, unit = Database.getHistoryInDays(int(amount)-1)
    if result == 'OK':
        return Response(json.dumps({'unit': unit, 'values': values, 'time_unit': days, 'error': None}), status=200, mimetype="application/json")
    else:
        return Response(json.dumps({'error':'There was an error'}), status=500, mimetype="application/json")


@weight_blueprint.route('/historyweeks', methods=['GET'])
def show_weeks():
    amount = request.args.get('amount')
    result, avg_values, day_in_week, unit = Database.getHistoryInWeeks(int(amount)-1)
    if result == 'OK':
        return Response(json.dumps({'unit': unit, 'values': avg_values, 'time_unit': day_in_week, 'error': None}), status=200, mimetype="application/json")
    else:
        return Response(json.dumps({'error':'There was an error'}), status=500, mimetype="application/json")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Weight logger</title>
    {% include 'html_dependencies.html' %}
</head>
<body>
<div class="container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

templates/history.html
{% extends 'base.html' %}
{% block content %}
{% include 'modals.html' %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.2/dist/Chart.bundle.min.js"></script>
<div class="jumbotron mt-3" id="jumbotron_container">
  <div class="row justify-content-center">
    <h1 class="display-4">Weekly and daily weight history chart</h1><br>
    <div class="col-lg-10 col-12">
      <div class="row">
        <div class="col-lg-2 col-3">
          <select class="form-control" id="selected_time_amount">
            {% for option in options %}
				<option value="{{option}}">{{option}}</option>
			{% endfor %}
          </select>
        </div>
        <div class="col-lg-2 col-5">
          <select class="form-control" id="selected_time_unit">
            <option value="days">Days</option>
            <option value="weeks">Weeks</option>
          </select>
        </div>
        <div class="col-lg-2 col-4">
          <button type="button" id="get_history" class="btn btn-primary">Get</button>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="chart_wrapper">
		      <canvas id="canvas" style="display:none;"></canvas>
	    </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-10 col-3">
      <a href="{{url_for('weight.register_weight')}}">Go back</a>
    </div>
  </div>
</div>
<script src="{{url_for('static', filename='js/chart-config.js')}}"></script>
<script>
  $('button#get_history').click(function(){
    var amount = $('#selected_time_amount option:selected').val();
    var time_unit = $('#selected_time_unit option:selected').val();
    var url = (time_unit == 'days') ? "{{url_for('weight.show_days')}}" :
      "{{url_for('weight.show_weeks')}}";
    $.ajax({
      url : url+"?amount="+amount,
      type: 'GET',
      contentType: 'application/json',
      dataType: 'json'
    }).always(function(weight_data){
      if(weight_data.error){
        $('#error_modal').modal('show')
        $('p#error').html(weight_data.error);
        return false;
      }
      if(weight_data.values.length == 0){
        $('#error_modal').modal('show')
        $('p#error').html("No data yet");
        $('#canvas').hide();
        return false;
      }
      //unit -> Y axis , values -> data, time_unit -> X Axis
      config.options.scales.yAxes[0].scaleLabel.labelString = weight_data.unit;
      config.data.datasets[0].data = weight_data.values;
      config.data.labels = weight_data.time_unit;
      myLineChart.update();
      $('#canvas').show();
    })
  })
</script>
{% endblock %}

templates/html_dependencies.html
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet">

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% include 'modals.html' %}
<div class="jumbotron mt-3" id="jumbotron_container">
  <h1 class="display-4">Log today's weight</h1><br>
  <div class="row justify-content-center">
    <div class="col-lg-4 col-sm-6">
      <input class="form-control" type="text" name="weight_input" placeholder="Enter today's weight"/>
    </div>
    <div class="col-lg-2 col-sm-2">
      <select class="form-control" id="selected_unit">
        <option value="kg">Kg</option>
        <option value="lb">Lb</option>
      </select>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-6 col-sm-6">
      <br>
      <button type="button" id="btn_submit" class="btn btn-primary btn-lg btn-block">Submit today's weight</button>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-6 col-sm-6">
      <br>
      <a href="{{url_for('weight.show_history')}}">Show history</a>
    </div>
  </div>
  {% if last_week_avg %}
    {% include 'week_avg_weight_template.html' %}
  {% endif %}
</div>
<script>
$(document).ready(function(){
  $('#btn_submit').click(function(){
    $.ajax({
      type: 'POST',
      url: '{{url_for('weight.register_weight')}}',
      data: JSON.stringify({
        todays_weight: $('input[name="weight_input"]').val(),
        unit: $('#selected_unit option:selected').val()
      }),
      contentType: 'application/json',
      dataType: 'json'
    }).always(function(data){
      if(data.error){
        $('#error_modal').modal('show')
        $('p#error').html(weight_data.error);
        return false;
      }
      if(data.last_week_avg)
        $('#week_avg').html("This week's average: " + data.last_week_avg + " " + data.unit)
      $('p#weight').html(data.weight + " " + data.unit)
      $('#weight_successfully_logged').modal('show');
      $('#weight_successfully_logged').on('hidden.bs.modal', function (e) {
        location.reload();
      })
    })
  })
})
</script>
{% endblock %}

templates/modals.html
<div id="weight_successfully_logged" class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal_custom_content_container">
          <div class="modal_container">
            <p>Your weight has been successfully logged! <i class="fa fa-check" aria-hidden="true" style="color:green;"></i><p/>
            <p id="weight"></p>
            <p id="week_avg"></p>
          </div>
      </div>
    </div>
  </div>
</div>

<div id="error_modal" class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal_custom_content_container">
          <div class="modal_container">
            <p id="error"></p><i class="fa fa-exclamation-triangle" aria-hidden="true" style="color:red;"></i>
          </div>
      </div>
    </div>
  </div>
</div>

templates/week_avg_weight_template.html
<div class='row justify-content-center'>
  <h4 id='avg_value'>This week's average weight: {{last_week_avg}} {{unit}}
  </h4>
</div>